package artist:tool@1.0.0;
interface send {
    use artist:%resource/types@1.0.0.{send-request, uri, error};
    send: func(requests: list<send-request>) -> list<result<uri, error>>;
}
world tool-world { export send; }
