[package]
name = "muse-classification"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
muse-core.workspace = true
muse-ontology.workspace = true
muse-registry.workspace = true
serde.workspace = true
thiserror.workspace = true
