package artist:tool@1.0.0;
interface grep {
    use artist:%resource/types@1.0.0.{anchored-text, error, uri};
    record grep-request { uri: uri, pattern: string }
    record grep-response { matches: list<anchored-text> }
    grep: func(requests: list<grep-request>) -> list<result<grep-response, error>>;
    observe: func(response: result<grep-response, error>) -> string;
}
world tool-world { export grep; }
