[package]
name = "artist-default-tools"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = "0.60.0"
artist-teca = { path = "../artist-teca" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
toon-format = { version = "0.5", default-features = false }
