package artist:url@1.0.0;

interface registry {
  resource registration;

  enum error {
    invalid-uri,
    conflict,
    not-found,
  }

  register: func(uri: string) -> result<registration, error>;
  unregister: func(value: registration) -> result<_, error>;
}

world url-root {
  import registry;
}
