[package]
name = "artist-plugin"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
artist-core = { path = "../artist-core" }
artist-resource = { path = "../artist-resource" }
async-trait.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true

[dev-dependencies]
tempfile.workspace = true
