package artist:tool@1.0.0;
interface write {
    use artist:%resource/types@1.0.0.{write-request, write-result, error};
    write: func(requests: list<write-request>) -> list<result<write-result, error>>;
}
world tool-world { export write; }
