use crate::sessions::ActiveSession;
use anyhow::Result;
use artist_session::{ContentBlock, HistoryCompact, HistoryOptions};
use llm_provider::SavedProvider;
use rig_core::completion::message::Message;

pub const PRESERVE_RECENT_TURNS: usize = 6;
pub const AUTO_TRIGGER_PERCENT: u64 = 75;

pub struct CompactionResult {
    pub history: Vec<Message>,
    pub compacted_events: usize,
}

pub fn should_compact(used_tokens: Option<u64>, capacity: Option<u64>) -> bool {
    matches!((used_tokens, capacity), (Some(used), Some(capacity)) if capacity > 0
        && used.saturating_mul(100) >= capacity.saturating_mul(AUTO_TRIGGER_PERCENT))
}

pub async fn compact(
    active: &ActiveSession,
    provider: &SavedProvider,
) -> Result<Option<CompactionResult>> {
    active.recorder.flush().await;
    let events = active.events()?;
    let Some(candidate) =
        artist_session::select_compaction_candidate(&events, PRESERVE_RECENT_TURNS)
    else {
        return Ok(None);
    };
    let source = artist_session::render_compaction_source(&candidate);
    let summary = artist_agent::compaction::summarize_history(provider, &source).await?;
    active.recorder.record(HistoryCompact {
        from_seq: candidate.from_seq,
        to_seq: candidate.to_seq,
        summary: vec![ContentBlock::Text {
            text: format!(
                "Historical session summary generated by Artist compaction:\n\n{}",
                summary.trim()
            ),
        }],
    });
    active.recorder.flush().await;
    let history = artist_session::build_history(
        &active.events()?,
        &active.attachments,
        &HistoryOptions::default(),
    )?;
    Ok(Some(CompactionResult {
        history,
        compacted_events: candidate.events.len(),
    }))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn trigger_is_conservative_and_requires_capacity() {
        assert!(!should_compact(Some(74), Some(100)));
        assert!(should_compact(Some(75), Some(100)));
        assert!(!should_compact(Some(90), None));
        assert!(!should_compact(Some(90), Some(0)));
    }
}
