// @generated by artist-anchor-address-lab. Do not hand-edit.
// This is the frozen address function only; CTM/BDM is not a runtime dependency.

pub const FIELD_PRIME: u64 = 68399;
#[allow(dead_code)]
pub const ADDRESS_ALPHABET_SIZE: usize = 68399;
pub const BYTE_CODEC_MULTIPLIER: u64 = 17;
pub const BYTE_CODEC_OFFSET: u64 = 17;
pub const OPTIMIZED_POINTS: &[u64] = &[49667, 38410, 64413, 58963];
pub const TAIL_OFFSET: u64 = 30920;
pub const TAIL_STEP: u64 = 8449;
const FIELD_POINT_COUNT: usize = (FIELD_PRIME - 1) as usize;

#[inline]
fn is_optimized_point(point: u64) -> bool {
    OPTIMIZED_POINTS.contains(&point)
}

fn point_at_slot(slot: usize) -> u64 {
    assert!(slot < FIELD_POINT_COUNT);
    if slot < OPTIMIZED_POINTS.len() {
        return OPTIMIZED_POINTS[slot];
    }
    let wanted = slot - OPTIMIZED_POINTS.len();
    let modulus = FIELD_PRIME - 1;
    let mut seen = 0usize;
    for n in 0..modulus {
        let point = 1 + ((TAIL_OFFSET + n * TAIL_STEP) % modulus);
        if is_optimized_point(point) {
            continue;
        }
        if seen == wanted {
            return point;
        }
        seen += 1;
    }
    unreachable!("tail permutation exhausted")
}

#[inline]
fn normal_eval(input: &[u8], point: u64) -> u64 {
    let mut value = 0u64;
    for &byte in input {
        let encoded = (BYTE_CODEC_MULTIPLIER * byte as u64 + BYTE_CODEC_OFFSET) % 729;
        let digits = [encoded / 81, (encoded / 9) % 9, encoded % 9];
        for digit in digits {
            value = (value * point + digit + 1) % FIELD_PRIME;
        }
    }
    // 10 is outside the source coefficient alphabet 1..=9 and terminates the
    // polynomial, preventing length/trailing-zero ambiguity.
    (value * point + 10) % FIELD_PRIME
}

fn mod_pow(mut base: u64, mut exp: u64) -> u64 {
    let mut out = 1u64;
    while exp != 0 {
        if exp & 1 != 0 { out = (out * base) % FIELD_PRIME; }
        base = (base * base) % FIELD_PRIME;
        exp >>= 1;
    }
    out
}

fn binom_small(n: u64, k: u64) -> u64 {
    if k > n { return 0; }
    let k = k.min(n - k);
    let mut numerator = 1u64;
    let mut denominator = 1u64;
    for i in 0..k {
        numerator = (numerator * (n - i)) % FIELD_PRIME;
        denominator = (denominator * (i + 1)) % FIELD_PRIME;
    }
    (numerator * mod_pow(denominator, FIELD_PRIME - 2)) % FIELD_PRIME
}

// Lucas' theorem makes the Hasse continuation valid for arbitrarily high orders.
fn binom_mod_prime(mut n: usize, mut k: usize) -> u64 {
    let p = FIELD_PRIME as usize;
    let mut out = 1u64;
    while n != 0 || k != 0 {
        let ni = n % p;
        let ki = k % p;
        if ki > ni { return 0; }
        out = (out * binom_small(ni as u64, ki as u64)) % FIELD_PRIME;
        n /= p;
        k /= p;
    }
    out
}

fn coefficients(input: &[u8]) -> Vec<u64> {
    let mut out = Vec::with_capacity(input.len() * 3 + 1);
    for &byte in input {
        let encoded = (BYTE_CODEC_MULTIPLIER * byte as u64 + BYTE_CODEC_OFFSET) % 729;
        out.push(encoded / 81 + 1);
        out.push((encoded / 9) % 9 + 1);
        out.push(encoded % 9 + 1);
    }
    out.push(10);
    out
}

fn hasse_eval(input: &[u8], point: u64, order: usize) -> u64 {
    if order == 0 { return normal_eval(input, point); }
    let coeffs = coefficients(input);
    let degree = coeffs.len() - 1;
    if order > degree { return 0; }
    let mut out = 0u64;
    for (index, &coefficient) in coeffs.iter().enumerate() {
        let power = degree - index;
        if power < order { continue; }
        let choose = binom_mod_prime(power, order);
        if choose == 0 { continue; }
        let term = (((choose * coefficient) % FIELD_PRIME)
            * mod_pow(point, (power - order) as u64)) % FIELD_PRIME;
        out = (out + term) % FIELD_PRIME;
    }
    out
}

/// Return one base-P component of the deterministic address stream.
///
/// Depths 0..P-2 evaluate the input polynomial at every nonzero field point in
/// the frozen optimized order. Later layers evaluate successive Hasse derivatives
/// at that same point order, so the mathematical address is defined for any finite
/// input rather than relying on a stateful or cryptographic fallback.
pub fn anchor_address_component(input: &[u8], depth: usize) -> u32 {
    let order = depth / FIELD_POINT_COUNT;
    let slot = depth % FIELD_POINT_COUNT;
    let point = point_at_slot(slot);
    hasse_eval(input, point, order) as u32
}

pub fn anchor_address_prefix(input: &[u8], components: usize) -> Vec<u32> {
    (0..components)
        .map(|depth| anchor_address_component(input, depth))
        .collect()
}
