package artist:tool@1.0.0;

interface insert {
    use artist:%resource/types@1.0.0.{anchor, anchored-text, anchored-diff, error, uri};
    variant insertion-position { top, bottom, at(anchor) }
    record insert-request { uri: uri, at: insertion-position, content: string }
    record insert-response { uri: uri, changed: list<anchored-text>, diff: anchored-diff }
    insert: func(requests: list<insert-request>) -> list<result<insert-response, error>>;
    observe: func(response: result<insert-response, error>) -> string;
}

world tool-world { export insert; }
